### ISSUE TITLE
Support other currencies than euro

### ISSUE THREAD

**Issue by theErikss0n** [matekasse/matekasse#4] opened 2021-08-04 19:26 UTC

**Comment by neilschark** [comment] 2021-08-06 16:41
My suggestion: Just add the option to change the symbol to whatever currency you like. For 99.999% of users the currency will be set one time and never change. Anything more complicated than that is out of scope for now IMHO.

**Comment by neilschark** [comment] 2021-08-12 18:45
duplicate of https://github.com/matekasse/matekasse/pull/101

**Closed** 2021-09-22 19:57 UTC
Labels: enhancement, Backend, Frontend
